// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCCNXjOSoyaL1g4LLGmVA-qeo6UFv5Is',
    appId: '1:71893083805:web:d7aa76d81404dfab5d9674',
    messagingSenderId: '71893083805',
    projectId: 'chatapptute-8039a',
    authDomain: 'chatapptute-8039a.firebaseapp.com',
    storageBucket: 'chatapptute-8039a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUj7eHCmGZsZAkMJKeYy4XxUDpwi5MrUs',
    appId: '1:71893083805:android:776eda56d7da64ae5d9674',
    messagingSenderId: '71893083805',
    projectId: 'chatapptute-8039a',
    storageBucket: 'chatapptute-8039a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAuQQ-5QW6tjOrHQj-v15KMMGGoN_Jmg',
    appId: '1:71893083805:ios:37010947eecc19a15d9674',
    messagingSenderId: '71893083805',
    projectId: 'chatapptute-8039a',
    storageBucket: 'chatapptute-8039a.appspot.com',
    iosBundleId: 'com.example.chatMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAuQQ-5QW6tjOrHQj-v15KMMGGoN_Jmg',
    appId: '1:71893083805:ios:922056909f4dd02a5d9674',
    messagingSenderId: '71893083805',
    projectId: 'chatapptute-8039a',
    storageBucket: 'chatapptute-8039a.appspot.com',
    iosBundleId: 'com.example.chatMessengerApp.RunnerTests',
  );
}
